const AUDIO_STATE_PAUSE = 0;

const AUDIO_STATE_PLAY = 1;

const AUDIO_STATE_WAITING = 2;

const AUDIO_STATE_END = 99;

module.exports = {
  AUDIO_STATE_PAUSE,
  AUDIO_STATE_PLAY,
  AUDIO_STATE_WAITING,
  AUDIO_STATE_END
}